* Using INDEX Function to Reshape and Aggregate Data in Excel

With ~INDEX()~ function data can be reshaped and aggregated in flexible ways.

** Reshaping Data

Let's suppose that the original data is in the first row of the spreadsheet (~A1:I1~).

|----+----+----+----+----+----+----+----+----|
| A1 | B1 | C1 | A2 | B2 | C2 | A3 | B3 | C3 |
|----+----+----+----+----+----+----+----+----|

We want to reshape this data in the form

|----+----+----|
| A1 | B1 | C1 |
| A2 | B2 | C2 |
| A3 | B3 | C3 |
|----+----+----|


Let's suppose that we want to put the first row of this table (the one starting with ~A1~) into the *second row* of the
spreadsheet. In this case the three cells of the first row of the reshaped data should contain

1. ~=INDEX($A$1:$I$1, 1, (ROW()-1)*3-2)~
2. ~=INDEX($A$1:$I$1, 1, (ROW()-1)*3-1)~
3. ~=INDEX($A$1:$I$1, 1, (ROW()-1)*3)~

After this, simple expanding the formulas to the whole table will result the data in the desired structure.

** Calculating Yeary Averages

Suppose that our data is in monthly frequency and is located in ~A1:A100~.

|-----|
| M1  |
| M2  |
| M3  |
| ... |
| M12 |
| M1  |
| ..  |

Our goal is to calculate an average value for each year.

Let's suppose again, that the first cell of our new data is in the second row (under e.g. a header) of the
spreadsheet. The yearly averages can be obtained in the rows of the new table by:

#+BEGIN_SRC 
=AVERAGE(INDEX($A$1:$A$100, (ROW()-1)*12-11, 1):INDEX($A$1:$A$100, (ROW()-1)*12, 1))
#+END_SRC
** 
